# TODO: to be implemented
# - optional type   : '?i32'
# - error type      : 'IoError!String'
# - error sets like in Zig
# - defer
# - different kinds of casts (normal cast, pun cast, ...)

# Ignore whitespaces -> ' ', '\t', '\n'
# Comment -> // ... \n and /* ... */ cannot be nested

# Keywords
# * Objects
#   - module
#   - struct
#   - union
#   - fun
# * Types
#   - void
#   - type
# * Constructs
#   - if
#   - else
#   - while
#   - do
#   - loop
#   - continue
#   - break
#   - return
# * Operators
#   - or
#   - and
#   - not
#   - true
#   - false
#   - as

# name : type
# name : const type
# name : type = value
# name : const type = value // same as name : type : value
# name := value
# name : type : value
# name : const type : value // const is redundant
# name :: value

Program     <- Decl*;

Decl        <- (Identifier / '_') ':' Type (';' / [=:] Object)
             | (Identifier / '_') ':' ([=:] Object)
             | 'use' Identifier ('.' Identifier)* ('.' '*'); ';'
Object      <- Module / Struct / Union / Function
             / 'type' Type ';'
             / Expr ';'
             ;
Module      <- 'module' (String ';' / '{' Decl* '}');
Struct      <- 'struct' '{' Fields '}';
Union       <- 'union' '{' Fields '}';
Function    <- 'fun' '(' Params ')' ('->' Type)? (';' / Block);

Fields      <- Field*;
Field       <- (Identifier / '_') ':' Type ([=:] Expr)? ';';

Params      <- (Param (',' Param)* ','?)?;
Param       <- Identifier ':' Type;

# Statements
Stmt            <- StmtIf / StmtWhile / StmtLoop # / StmtFor
                 / Block
                 / 'yield' Label? Expr ';'
                 / 'continue' Label? ';'
                 / 'break' Label? Expr? ';'
                 / 'return' Expr? ';'
                 / Expr ';'
                 / ';'
                 ;
Block           <- Label? '{' (Decl / Stmt)* '}';

# The blocks used have no label
StmtIf      <- 'if' Expr Block ('else' Block)?
StmtWhile   <- Label? 'while' Expr Block ('else' Block)?;
StmtLoop    <- Label? 'loop' Block;
# ExprFor     <- 'for' Block ('else' Block)?;

# Type
# - identifier  : 'i32'
# - const       : 'const i32'
# - function    : 'fun(i32, i32) -> bool'
# - pointer     : '*fun(i32,i32) -> bool' or '*i32'
# - array       : '[8] i32' or '[_] i32'
# - fat pointer : '[] u8'
# - tuple       : '(i32, bool)'
# - void        : 'void' or '()'
# - noreturn    : noreturn
# - type        : 'typedef'

Types   <- (Type (',' Type) ','?)?;
TypeFunctionParam <- (Identifier ':')? Type
Type    <-  Identifier ('.' Identifier)*
         / 'fun' '(' TypeFunctionParams ')' '->' Type
         / 'const' Type
         / '*' Type
         / '[' (Expr | '_') ']' Type
         / '['']' Type
         / '(' Type ')'
         / '(' Types ')'
         / 'void'
         / 'noreturn'
         / 'typedef'
         ;

# Expression
Exprs       <- (Expr (',' Expr) ','?)?;
Expr        <- LogicOr / Assignment;
Assignment  <- LogicOrs Operator '=' Exprs;
Operator    <- [+-][%:]?
             / [/%]
             / '*''*'?
             / '<''<' / '>''>'
             / [&|^];

LogicOr     <- LogicAnd ('or' LogicAnd)*;
LogicAnd    <- LogicNot ('and' LogicNot)*;
LogicNot    <- 'not'* Relational;
Relational  <- BitOr (('<'/'<='/'=='/'!='/'>='/'>') BitOr)*;
BitOr       <- BitXor ('|' BitXor)*;
BitXor      <- BitAnd ('^' BitAnd)*;
BitAnd      <- Shift ('&' Shift)*;
Shift       <- Term (('<''<'/'>''>') Term)*;
Term        <- Factor ([+-][%:]? Factor)*;
Factor      <- Power ([*/%] Power)*;
Power       <- (Cast '**')* Cast;
Cast        <- Unary ('as' Type)*;

Unary       <- Postfix
             / ('typeof'/'sizeof')? [-~*&]* Postfix;
Postfix     <- Primary
             (('.' Identifier)
            / ('(' Arguments ')')
            / ('[' Exprs ']'));
Arguments   <- (Argument (',' Argument)* ','?)?;
Argument    <- (Identifier ':')? Expr;
Primary     <- 'true' / 'false'
             / Integer / Float / Identifier
             / '(' Expr ')'
             / '(' Exprs ')'
             / '[' Exprs ']'
             / CompoundExpr;

CompoundExpr    <- Block
                 / ExprIf
                 / ExprWhile
                 / ExprLoop
                 / 'continue' Label?
                 / 'break' Label? Expr?
                 / 'return' Label? Expr?
                 ;

ExprIf      <- 'if' Expr Block ('else' Block)?
             / 'if' Expr 'then' Expr 'else' Expr;
ExprWhile   <- Label? 'while' Expr Block ('else' Block)?;
ExprLoop    <- Label? 'loop' Block;
# ExprFor     <- 'for' Block ('else' Block)?;

# Lexer definitions
Label       <-  '$' Identifier
Identifier  <- [a-zA-Z_][a-zA-Z0-9]*;

String      <- [a-zA-Z]? ["] .* !'\n' ["]        # Single line strings
            / [a-zA-Z]? '`' .* '`'               # Multi line strings
            ;

Integer     <- RawInteger ('i8'/'i16'/'i32'/'i64'/'i128'/'isize'/'u8'/'u16'/'u32'/'u64'/'u128'/'usize')?;
RawInteger  <- Decimal
            / '0'[bB]([01]_?)+
            / '0'[oO]([0-7]_?)+
            / '0'[xX] hex
            ;

Float       <- RawFloat ('f16'/'f32'/'f64')?;
RawFloat    <- Decimal '.' Decimal? ([eE][+-] Decimal)?
            / '0'[xX] hex '.' hex  ([pP][+-] Decimal)?
            ;

Decimal     <- ([0-9]_?)+;
Hex         <- ([0-9a-fA-F]_?)+;
